Added path of module being loaded to sys.path
- If path not added, the import would fail with:
  ImportError: No module named _ecmd
  This was because it couldn't find the .so

Signed-off-by: Jason Albert <albertj@us.ibm.com>