Fix undefined git_version symbol in dllNetwork
Commit 356569b ("Return the git hash for `croquery serverversion`")
added a dependency of server/ControlInstruction.C on
git_version.C. However, server/ControlInstruction.C is also used in
dllNetwork. Because git_version.C isn't used when compiling
dllNetwork, there is a runtime error when attempting to use the
resulting network.dll.

ERROR: loadDll: Problems loading eCMD/out_x86_64/lib/network.dll : eCMD/out_x86_64/lib/network.dll: undefined symbol: git_version
dllLoadDllRecovery: eCMD Function called before DLL has been loaded

Resolve this issue by calling the generate target of server when
building dllNetwork in order to create the necessary git_version.C.